In [1]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [2]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
# oov_token = we replace new word that are not present in our dataset as nothing

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index

{'india': 1,
 'jeetega': 2,
 'hip': 3,
 'ki': 4,
 'jai': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'modi': 14,
 'ji': 15,
 'inquilab': 16,
 'zindabad': 17}

In [6]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [7]:
#Total number of rows
tokenizer.document_count

10

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [9]:
from keras.utils import pad_sequences

In [10]:
sequences_post = pad_sequences(sequences,padding='post')

In [11]:
sequences_post

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [12]:
sequences_pre = pad_sequences(sequences,padding='pre')
sequences_pre

array([[ 0,  0,  0,  9,  1],
       [ 0,  0,  0,  1,  1],
       [ 0,  0,  3,  3, 10],
       [ 2, 11,  2,  1,  2],
       [ 0, 12, 13,  4,  5],
       [ 0,  0,  0,  6,  6],
       [ 0,  0,  0,  7,  7],
       [ 0,  0,  0,  8,  8],
       [ 0, 14, 15,  4,  5],
       [ 0,  0,  0, 16, 17]])

In [13]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.compile('adam','accuracy')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [14]:
pred = model.predict(sequences_post)
print(pred)

1/1 [==============================] - 0s 74ms/step
[[[-0.00666513  0.01738321]
  [-0.04922694  0.01444939]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04922694  0.01444939]
  [-0.04922694  0.01444939]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.03856826 -0.04991071]
  [-0.03856826 -0.04991071]
  [ 0.03341254 -0.03566463]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04244253 -0.02586235]
  [ 0.02696044 -0.04690727]
  [-0.04244253 -0.02586235]
  [-0.04922694  0.01444939]
  [-0.04244253 -0.02586235]]

 [[ 0.04798038 -0.0377639 ]
  [-0.00474184 -0.01168557]
  [ 0.01238568 -0.0217575 ]
  [-0.04312894 -0.04867965]
  [-0.01688384  0.00870061]]

 [[ 0.00488174 -0.03200697]
  [ 0.00488174 -0.03200697]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04981227  0.03949412]
  [-0.04981227  0.03949412]
  [-0.01688384  0.00870061]
  [-0.016883

# Building Sentimental Analysis using embedding

In [15]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [16]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [17]:
# find max length
max([len(i) for i in X_train])

2494

In [18]:
min([len(i) for i in X_train])

11

In [19]:
X_train.shape

(25000,)

In [20]:
# Total number of word presnt in X_train
max([max(i) for i in X_train])  

88586

In [21]:
# Total number of word present in X_train
x = []

for i in X_train:
    for j in i:
        x.append(j)
max(x)

88586

In [22]:
len(set(x))

88585

In [23]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [24]:
X_train.shape

(25000, 50)

In [25]:
model = Sequential()
model.add(Embedding(88585,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             177170    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 178,323
Trainable params: 178,323
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

history = model.fit(X_train,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
782/782 [==============================] - 86s 101ms/step - loss: 0.6113 - accuracy: 0.6312 - val_loss: 0.4396 - val_accuracy: 0.7996
Epoch 2/20
782/782 [==============================] - 73s 93ms/step - loss: 0.3655 - accuracy: 0.8425 - val_loss: 0.4284 - val_accuracy: 0.8114
Epoch 3/20
782/782 [==============================] - 68s 87ms/step - loss: 0.2447 - accuracy: 0.9067 - val_loss: 0.6145 - val_accuracy: 0.7816
Epoch 4/20
782/782 [==============================] - 73s 94ms/step - loss: 0.1750 - accuracy: 0.9377 - val_loss: 0.5407 - val_accuracy: 0.7946
Epoch 5/20
782/782 [==============================] - 73s 94ms/step - loss: 0.1238 - accuracy: 0.9578 - val_loss: 0.5623 - val_accuracy: 0.7893
Epoch 6/20
782/782 [==============================] - 73s 93ms/step - loss: 0.0889 - accuracy: 0.9715 - val_loss: 0.6553 - val_accuracy: 0.7809
Epoch 7/20
782/782 [==============================] - 75s 96ms/step - loss: 0.0705 - accuracy: 0.9774 - val_loss: 0.7421 - val_accuracy

In [ ]:
import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

In [ ]:
plt.plot(history.history['loss'],color='red',label='train')
plt.plot(history.history['val_loss'],color='blue',label='validation')
plt.legend()
plt.show()