In [1]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [2]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [4]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')
# oov_token = we replace new word that are not present in our dataset as nothing

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index 
# unique word and how many times it is assigned

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [8]:
tokenizer.word_counts

# word count

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [9]:
#Total number of rows
tokenizer.document_count

10

In [10]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [11]:
from keras.utils import pad_sequences

In [12]:
sequences_post = pad_sequences(sequences,padding='post')

In [13]:
sequences_post

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]])

In [14]:
sequences_pre = pad_sequences(sequences,padding='pre')
sequences_pre

array([[ 0,  0,  0, 10,  2],
       [ 0,  0,  0,  2,  2],
       [ 0,  0,  4,  4, 11],
       [ 3, 12,  3,  2,  3],
       [ 0, 13, 14,  5,  6],
       [ 0,  0,  0,  7,  7],
       [ 0,  0,  0,  8,  8],
       [ 0,  0,  0,  9,  9],
       [ 0, 15, 16,  5,  6],
       [ 0,  0,  0, 17, 18]])

In [13]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.compile('adam','accuracy')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [14]:
pred = model.predict(sequences_post)
print(pred)

1/1 [==============================] - 0s 74ms/step
[[[-0.00666513  0.01738321]
  [-0.04922694  0.01444939]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04922694  0.01444939]
  [-0.04922694  0.01444939]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.03856826 -0.04991071]
  [-0.03856826 -0.04991071]
  [ 0.03341254 -0.03566463]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04244253 -0.02586235]
  [ 0.02696044 -0.04690727]
  [-0.04244253 -0.02586235]
  [-0.04922694  0.01444939]
  [-0.04244253 -0.02586235]]

 [[ 0.04798038 -0.0377639 ]
  [-0.00474184 -0.01168557]
  [ 0.01238568 -0.0217575 ]
  [-0.04312894 -0.04867965]
  [-0.01688384  0.00870061]]

 [[ 0.00488174 -0.03200697]
  [ 0.00488174 -0.03200697]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]
  [-0.01688384  0.00870061]]

 [[-0.04981227  0.03949412]
  [-0.04981227  0.03949412]
  [-0.01688384  0.00870061]
  [-0.016883

# Building Sentimental Analysis using embedding

In [15]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 3s 0us/step


In [16]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [17]:
# find max length
max([len(i) for i in X_train])

2494

In [18]:
min([len(i) for i in X_train])

11

In [19]:
X_train.shape

(25000,)

In [20]:
# Total number of word presnt in X_train
max([max(i) for i in X_train])  

88586

In [21]:
# Total number of word present in X_train
x = []

for i in X_train:
    for j in i:
        x.append(j)
max(x)

88586

In [22]:
len(set(x))

88585

In [18]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [19]:
X_train.shape

(25000, 50)

In [20]:
model = Sequential()
model.add(Embedding(88585,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 2)             177170    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 178,323
Trainable params: 178,323
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

history = model.fit(X_train,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
782/782 [==============================] - 81s 94ms/step - loss: 0.6077 - accuracy: 0.6410 - val_loss: 0.4548 - val_accuracy: 0.7927
Epoch 2/20
782/782 [==============================] - 75s 95ms/step - loss: 0.3595 - accuracy: 0.8460 - val_loss: 0.4238 - val_accuracy: 0.8064
Epoch 3/20
782/782 [==============================] - 74s 95ms/step - loss: 0.2440 - accuracy: 0.9052 - val_loss: 0.4708 - val_accuracy: 0.7981
Epoch 4/20
782/782 [==============================] - 82s 105ms/step - loss: 0.1649 - accuracy: 0.9400 - val_loss: 0.5137 - val_accuracy: 0.7704
Epoch 5/20
782/782 [==============================] - 75s 96ms/step - loss: 0.1175 - accuracy: 0.9594 - val_loss: 0.6569 - val_accuracy: 0.7850
Epoch 6/20
782/782 [==============================] - 82s 105ms/step - loss: 0.0816 - accuracy: 0.9744 - val_loss: 0.7219 - val_accuracy: 0.7826
Epoch 7/20
782/782 [==============================] - 80s 102ms/step - loss: 0.0584 - accuracy: 0.9822 - val_loss: 0.7359 - val_accura

In [22]:
import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
plt.plot(history.history['loss'],color='red',label='train')
plt.plot(history.history['val_loss'],color='blue',label='validation')
plt.legend()
plt.show()