In [1]:
import torch

In [2]:
print(torch.cuda.is_available())

True


In [4]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device="cuda")
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [7]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device="cuda",requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device=device,requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [9]:
x.dtype

torch.float32

In [10]:
x.device

device(type='cuda', index=0)

In [11]:
x.shape

torch.Size([2, 3])

In [12]:
x.requires_grad

True

# Other common initialization methods

In [13]:
tens = torch.randn(6).reshape(6,1)
tens

tensor([[-0.8871],
        [ 0.8001],
        [ 0.4616],
        [ 1.3223],
        [-1.6414],
        [ 0.2689]])

In [16]:
assert type(tens)==torch.Tensor

In [10]:
type(tens)

torch.Tensor

In [11]:
l = [1,2,3,4,5,6]
assert type(l)==list

In [7]:
from collection.Collection import Counter

In [8]:
cnt = Counter()
for word in ['red', 'blue', 'red', 'green', 'blue', 'blue']:
    cnt[word] += 1

In [9]:
cnt

Counter({'blue': 3, 'red': 2, 'green': 1})

In [13]:
1e-6*1

1e-06

In [14]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])