In [1]:
import torch

In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
torch.ones(10) * 2

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [9]:
data = np.arange(10)
torch.from_numpy(data)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [10]:
t1 = torch.tensor(4,) # Scaler
t1

tensor(4)

In [11]:
t2 = torch.tensor([1, 2, 3,4])
t2

tensor([1, 2, 3, 4])

In [ ]:
t3 = 