In [1]:
import torch

In [4]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([1.3153, 1.0754, 1.3942], requires_grad=True)


In [5]:
y = x+2

In [6]:
y

tensor([3.3153, 3.0754, 3.3942], grad_fn=<AddBackward0>)

In [7]:
z = y*y*2

In [8]:
z

tensor([21.9830, 18.9161, 23.0410], grad_fn=<MulBackward0>)

In [9]:
z.mean()

tensor(21.3134, grad_fn=<MeanBackward0>)

In [14]:
z.backward(x)

In [16]:
x.grad

tensor([17.4432, 13.2291, 18.9285])