In [1]:
import torch

x = torch.empty(3)

In [2]:
x

tensor([9.1477e-41,        nan, 1.1210e-44])

In [3]:
x = torch.empty(2,2,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [4]:
x = torch.empty(2,3,4,5)
x

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])

In [5]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [6]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [7]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [8]:
print(x.dtype)

torch.float32


In [9]:
x = torch.ones(2,2,dtype=int)
x

tensor([[1, 1],
        [1, 1]])

In [10]:
print(x.dtype)

torch.int64


In [11]:
x = torch.ones(2,2,dtype=torch.double)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [12]:
x = torch.ones(2,2,dtype=torch.float16)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [13]:
x.size()

torch.Size([2, 2])

In [14]:
x = torch.tensor([2.5,1])
x

tensor([2.5000, 1.0000])

In [15]:
x = torch.rand(2,2)
x

tensor([[0.0628, 0.4144],
        [0.7854, 0.0755]])

In [16]:
y = torch.rand(2,2)
y

tensor([[0.9050, 0.3387],
        [0.6803, 0.7749]])

In [17]:
z = x + y
z

tensor([[0.9678, 0.7531],
        [1.4657, 0.8504]])

In [18]:
z = torch.add(x,y)
z

tensor([[0.9678, 0.7531],
        [1.4657, 0.8504]])

In [19]:
# modify element
y.add_(x)
y

tensor([[0.9678, 0.7531],
        [1.4657, 0.8504]])

In [20]:
# substraction
z = x - y
z

tensor([[-0.9050, -0.3387],
        [-0.6803, -0.7749]])

In [21]:
z = torch.sub(x,y)
z

tensor([[-0.9050, -0.3387],
        [-0.6803, -0.7749]])

In [22]:
# multiplication
z = x * y
z

tensor([[0.0607, 0.3121],
        [1.1512, 0.0642]])

In [23]:
z = torch.multiply(x,y)
z

tensor([[0.0607, 0.3121],
        [1.1512, 0.0642]])

In [24]:
z = torch.mul(x,y)
z

tensor([[0.0607, 0.3121],
        [1.1512, 0.0642]])

In [25]:
y.mul_(x)
y

tensor([[0.0607, 0.3121],
        [1.1512, 0.0642]])

In [26]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [27]:
z = x/y
z

tensor([[ 0.0343,  5.0902],
        [25.5753,  1.1940]])

In [28]:
x = torch.rand(5,3)
print(x)

tensor([[0.5576, 0.2548, 0.1353],
        [0.3552, 0.7158, 0.4366],
        [0.4769, 0.8362, 0.7368],
        [0.8738, 0.1131, 0.9251],
        [0.9712, 0.0460, 0.8097]])


In [29]:
print(x[:,0])

tensor([0.5576, 0.3552, 0.4769, 0.8738, 0.9712])


In [30]:
print(x[0,:])

tensor([0.5576, 0.2548, 0.1353])


In [31]:
print(x[1,1])

tensor(0.7158)


In [32]:
# If one element in our tensor
print(x[1,1].item())

0.7157614231109619


In [33]:
# tensor behaves as matrix
x = torch.rand(2,3)
y = torch.rand(2,2)
z = x*y
z

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [34]:
x = torch.rand(4,4)
print(x)

tensor([[0.1485, 0.2003, 0.6925, 0.2439],
        [0.6407, 0.8830, 0.3276, 0.1027],
        [0.4107, 0.2382, 0.6592, 0.8414],
        [0.3273, 0.2454, 0.3428, 0.7284]])


In [35]:
# like reshape in numpy we use view in pytorch
y = x.view(16)
y

tensor([0.1485, 0.2003, 0.6925, 0.2439, 0.6407, 0.8830, 0.3276, 0.1027, 0.4107,
        0.2382, 0.6592, 0.8414, 0.3273, 0.2454, 0.3428, 0.7284])

In [36]:
x = torch.rand(4,4)
y = x.view(-1,8) # In view method in torch if we set one value -1 it reflect with another value only other value set in accordingly
y

tensor([[0.1039, 0.4593, 0.1891, 0.4465, 0.5753, 0.3388, 0.4509, 0.5014],
        [0.7240, 0.2008, 0.7396, 0.1832, 0.4611, 0.3479, 0.5038, 0.9049]])

In [37]:
y = x.view(8,-1)
y

tensor([[0.1039, 0.4593],
        [0.1891, 0.4465],
        [0.5753, 0.3388],
        [0.4509, 0.5014],
        [0.7240, 0.2008],
        [0.7396, 0.1832],
        [0.4611, 0.3479],
        [0.5038, 0.9049]])

In [38]:
y = x.view(16,-1) # In view  
y

tensor([[0.1039],
        [0.4593],
        [0.1891],
        [0.4465],
        [0.5753],
        [0.3388],
        [0.4509],
        [0.5014],
        [0.7240],
        [0.2008],
        [0.7396],
        [0.1832],
        [0.4611],
        [0.3479],
        [0.5038],
        [0.9049]])

In [39]:
y.shape

torch.Size([16, 1])

In [40]:
y = x.view(-1,16) # In view 
y

tensor([[0.1039, 0.4593, 0.1891, 0.4465, 0.5753, 0.3388, 0.4509, 0.5014, 0.7240,
         0.2008, 0.7396, 0.1832, 0.4611, 0.3479, 0.5038, 0.9049]])

In [41]:
y.shape

torch.Size([1, 16])

In [42]:
y.size()

torch.Size([1, 16])

In [43]:
# converting numpy to torch tensor
import numpy as np

In [44]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [45]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [46]:
a = torch.from_numpy(b)
a

tensor([1., 1., 1., 1., 1.])

In [47]:
a = torch.ones(5)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [48]:
a = np.ones(5)
b = torch.from_numpy(a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [49]:
a = np.ones(5)
b = torch.from_numpy(a)

b = b.type(torch.int)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [50]:
x = torch.ones(2,2,dtype=int)
x

tensor([[1, 1],
        [1, 1]])

In [51]:
x += 1
x

tensor([[2, 2],
        [2, 2]])

In [52]:
if torch.cuda.is_available:
    device = torch.device('cuda')
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x * y
    #z.numpy()
    z = z.to('cpu')

In [53]:
z

tensor([1., 1., 1., 1., 1.])

In [54]:
torch.cuda.is_available()

True

In [55]:
a = torch.ones(5, requires_grad = True)
a

tensor([1., 1., 1., 1., 1.], requires_grad=True)