In [2]:
import torch

In [3]:
print(torch.cuda.is_available())

True


In [4]:
x = torch.empty(1)
x

tensor([1.4450e-34])

In [5]:
x = torch.empty(3,2)
x

tensor([[1.4595e-34, 1.7839e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [6]:
x = torch.empty(2,2,3,4)
x

tensor([[[[1.4746e-34, 1.7839e-42, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]]])

In [7]:
x = torch.zeros(2,2,3,4)
x

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [8]:
x = torch.ones(2,2,3,4)
x

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [9]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy to torch

In [10]:
import numpy as np
data = np.arange(10)
torch.from_numpy(data)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [11]:
t1 = torch.tensor(4,) # Scaler
t1

tensor(4)

In [12]:
t2 = torch.tensor([1, 2, 3,4]) # Vector
t2

tensor([1, 2, 3, 4])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32,device="cuda")
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [15]:
tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32,device="cuda", requires_grad=True)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [16]:
devices = "cuda" if torch.cuda.is_available() else "cpu"

In [17]:
tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32,device=devices, requires_grad=True)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [18]:
print(tensor.dtype)

torch.float32


In [19]:
print(tensor.device)

cuda:0


In [20]:
print(tensor.shape)

torch.Size([2, 3])


In [21]:
print(tensor.requires_grad)

True


In [28]:
x = torch.rand((3,3),device=devices,requires_grad=True)
x

tensor([[0.6212, 0.1133, 0.1423],
        [0.4710, 0.6953, 0.3413],
        [0.9754, 0.6216, 0.3131]], device='cuda:0', requires_grad=True)

In [32]:
x=torch.tensor(5.0,requires_grad=True)
f = 2*(x**2) +5
f

tensor(55., grad_fn=<AddBackward0>)

In [33]:
f.backward()

In [34]:
print(x.grad)

tensor(20.)


In [35]:
x = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [36]:
 
def f(x):
    return 2*(x**3) + 5*(x**2) + 7*x + 10
 
print(f(x))

tensor([[ 24.,  60., 130.],
        [246., 420., 664.]], grad_fn=<AddBackward0>)


In [37]:
 
gred = torch.autograd.functional.jacobian(f, x)
print(gred.shape)
gred

torch.Size([2, 3, 2, 3])


tensor([[[[ 23.,   0.,   0.],
          [  0.,   0.,   0.]],

         [[  0.,  51.,   0.],
          [  0.,   0.,   0.]],

         [[  0.,   0.,  91.],
          [  0.,   0.,   0.]]],


        [[[  0.,   0.,   0.],
          [143.,   0.,   0.]],

         [[  0.,   0.,   0.],
          [  0., 207.,   0.]],

         [[  0.,   0.,   0.],
          [  0.,   0., 283.]]]])

# https://www.geeksforgeeks.org/how-to-differentiate-a-gradient-in-pytorch/

In [39]:
x = torch.rand((3,3),device=devices, requires_grad=True)
x

tensor([[0.8674, 0.1246, 0.9618],
        [0.5735, 0.9308, 0.7109],
        [0.2897, 0.7313, 0.6620]], device='cuda:0', requires_grad=True)

In [41]:
f = x**2

In [42]:
f

tensor([[0.7524, 0.0155, 0.9250],
        [0.3289, 0.8665, 0.5053],
        [0.0839, 0.5348, 0.4382]], device='cuda:0', grad_fn=<PowBackward0>)

In [43]:
x = torch.eye(5,device=devices)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0')

In [45]:
x = torch.arange(1,100, device=devices)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99], device='cuda:0')

In [46]:
x = torch.linspace(0,100,5)
x

tensor([  0.,  25.,  50.,  75., 100.])

In [47]:
x = torch.empty(100).normal_(mean=0,std=1)
x

tensor([-0.2650,  0.0552,  0.6338, -0.8139,  0.4894,  0.4256,  1.2669, -0.0128,
        -0.1072, -1.1654,  0.8652,  1.1310, -0.9676, -0.5675,  1.4768,  0.4090,
        -0.8461, -0.3590,  2.9325, -0.5709, -0.9938, -0.8991,  0.0914,  1.3893,
         0.3474, -0.2479,  0.6686,  1.4162,  0.2429, -0.1041,  1.0442, -0.2989,
        -0.0696,  0.3454,  0.3641, -1.7143,  2.0429, -1.7563, -1.8084, -0.3835,
        -1.3294,  0.0582,  0.5220,  0.0969,  0.2891,  1.7285, -0.4863,  0.9627,
        -0.0064, -1.2433, -0.3022,  1.3084,  0.7970, -0.7216, -0.4289,  0.9961,
         0.8048, -0.9921,  1.2465,  0.2753, -0.4853,  1.3360,  1.3359, -0.2018,
        -0.4576, -0.9668, -0.4459, -0.0121, -0.5802, -1.8395, -0.3027, -1.0341,
        -0.2563,  1.1524,  0.9153,  1.1895,  1.2079, -0.8985,  1.2459,  0.8267,
         0.5770,  0.9616, -0.3470,  1.2698,  0.8894, -1.4290,  0.1846,  1.9639,
        -1.6162,  1.8378,  0.1048,  1.4405, -0.2849,  1.0632,  0.2275, -1.1681,
         0.3014,  0.4158,  0.1455,  0.37

In [3]:
x = "hello"

#if condition returns True, then nothing happens:
assert x == "hello"

#if condition returns False, AssertionError is raised:
assert x == "goodbye"

AssertionError: 

In [4]:
x = 546
assert type(x) == int

In [5]:
from collections import Counter

In [8]:
1e-6 *1000

0.001