In [1]:
import torch

In [2]:
print(torch.cuda.is_available())

True


In [4]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device="cuda")
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [7]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device="cuda",requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,device=device,requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [9]:
x.dtype

torch.float32

In [10]:
x.device

device(type='cuda', index=0)

In [11]:
x.shape

torch.Size([2, 3])

In [12]:
x.requires_grad

True

# Other common initialization methods