In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\2065005710.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


2.2.0+cu118


In [2]:
# scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get tensor back as python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
# RANDOM

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9666, 0.5736, 0.9675, 0.0921],
        [0.3403, 0.6602, 0.1584, 0.2663],
        [0.7633, 0.4009, 0.0252, 0.7254]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor = torch.rand(1000000000)
random_tensor

tensor([0.9552, 0.9136, 0.9091,  ..., 0.5208, 0.8434, 0.6212])

In [18]:
random_tensor.shape

torch.Size([1000000000])

In [19]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8725, 0.5244, 0.9938, 0.1070],
        [0.2381, 0.1699, 0.4231, 0.9849],
        [0.5184, 0.2148, 0.3651, 0.6121]])

In [20]:
random_tensor.ndim

2

In [21]:
# create a random trensor with similar to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channels (red, Green , Blue) 

In [22]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [23]:
random_image_size_tensor.ndim

3

In [24]:
random_image_size_tensor

tensor([[[0.4221, 0.9174, 0.3882],
         [0.9954, 0.2200, 0.2132],
         [0.2251, 0.6439, 0.9334],
         ...,
         [0.9236, 0.6042, 0.2087],
         [0.8196, 0.5997, 0.4493],
         [0.3815, 0.9069, 0.1707]],

        [[0.2278, 0.3744, 0.9779],
         [0.9527, 0.3779, 0.2489],
         [0.5469, 0.1977, 0.6134],
         ...,
         [0.0400, 0.3737, 0.7880],
         [0.9771, 0.4032, 0.7314],
         [0.3573, 0.3724, 0.0163]],

        [[0.0049, 0.7017, 0.1783],
         [0.9679, 0.7569, 0.4781],
         [0.0875, 0.2029, 0.9466],
         ...,
         [0.3692, 0.0295, 0.8718],
         [0.9895, 0.2799, 0.6657],
         [0.7281, 0.7981, 0.6379]],

        ...,

        [[0.2499, 0.6371, 0.1962],
         [0.6795, 0.9926, 0.7238],
         [0.8749, 0.5573, 0.1749],
         ...,
         [0.5625, 0.3155, 0.5209],
         [0.8939, 0.0625, 0.4873],
         [0.6970, 0.5251, 0.8901]],

        [[0.9649, 0.1291, 0.7526],
         [0.5856, 0.2880, 0.2538],
         [0.

In [25]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
# Range of tensor and tensorlike

torch.range(0,10)

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\789399331.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.arange(0,11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.arange(0,100,5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [32]:
ten_zeros = torch.zeros_like(input=ones)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# Tensor DataType

float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [35]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.double)
float_64_tensor.dtype

torch.float64

In [36]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.short)
float_16_tensor.dtype

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\2914693274.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.short)


torch.int16

In [37]:
tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.double, device='cuda')
tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)

In [38]:
tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.double, device='cuda', requires_grad=False)
tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)

# ERROR
- Not right datatype
- not right shape
- not on the right device

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.int)
int_32_tensor.dtype

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\2785990277.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.int)


torch.int32

In [42]:
int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.short)
int_32_tensor.dtype

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\2613421198.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.short)


torch.int16

In [43]:
int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.long)
int_32_tensor.dtype

C:\Users\Nihar\AppData\Local\Temp\ipykernel_18244\3013046536.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  int_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.long)


torch.int64

In [44]:
tensor = torch.rand(3,4)
tensor

tensor([[0.5631, 0.8157, 0.6626, 0.9588],
        [0.0399, 0.5327, 0.3418, 0.7744],
        [0.2704, 0.6227, 0.6165, 0.4516]])

In [45]:
tensor.shape

torch.Size([3, 4])

In [46]:
tensor.dtype

torch.float32

In [47]:
tensor.device

device(type='cpu')

In [48]:
tensor = torch.rand(3,4, device='cuda')
tensor.device

device(type='cuda', index=0)

In [49]:
### manipulating Tensor (tensor operations)

In [50]:
# create atensor and add 10
tensor = torch.tensor([1,2,3,])
tensor + 10

tensor([11, 12, 13])

In [51]:
# Multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [52]:
tensor - 10

tensor([-9, -8, -7])

In [53]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [54]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [55]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [56]:
tensor * tensor

tensor([1, 4, 9])

In [57]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [58]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 2.31 ms


tensor(14)

In [59]:
import tqdm

In [60]:
from tqdm.notebook import tqdm_notebook
import time
for i in tqdm_notebook(range(10)):
    time.sleep(0.5)

  0%|          | 0/10 [00:00<?, ?it/s]

In [61]:
A = torch.rand(3,3)
B = torch.rand(3,3)

In [62]:
A

tensor([[0.1036, 0.9326, 0.2973],
        [0.6698, 0.1146, 0.6822],
        [0.3237, 0.0662, 0.8061]])

In [63]:
B

tensor([[0.7793, 0.6318, 0.7472],
        [0.7507, 0.4139, 0.9943],
        [0.6305, 0.6776, 0.4900]])

In [64]:
A_rows = len(A)
A_cols = len(A[0])
B_rows = len(B)
B_cols = len(B[0])

    # # Check if the matrices can be multiplied
    # if A_cols != B_rows:
    #     raise ValueError("Number of columns in A must be equal to number of rows in B")

In [65]:
result = torch.tensor([[0] * B_cols for _ in range(A_rows)])
result

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [66]:
A = torch.tensor([[1, 2], [3,4]])
B =A

A_rows = len(A)
A_cols = len(A[0])
B_rows = len(B)
B_cols = len(B[0])

result = torch.tensor([[0] * B_cols for _ in range(A_rows)])
for i in range(A_rows):
    for j in range(B_cols):
        sum = 0
        for k in range(A_cols):
            sum += A[i][k] * B[k][j]
        result[i][j] = sum
result      

tensor([[ 7, 10],
        [15, 22]])

In [67]:
A*A # Elementwise multiplication

tensor([[ 1,  4],
        [ 9, 16]])

In [68]:
for i in range(A_rows):
    print(A[i])

tensor([1, 2])
tensor([3, 4])


In [69]:
torch.matmul(A,A)

tensor([[ 7, 10],
        [15, 22]])

In [70]:
torch.mm(A,A)

tensor([[ 7, 10],
        [15, 22]])

In [71]:
A.T

tensor([[1, 3],
        [2, 4]])

In [72]:
torch.mm(A,A.T)

tensor([[ 5, 11],
        [11, 25]])

In [73]:
A.shape,A.T.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

# Tensor Aggregation

In [74]:
x = torch.arange(0, 100, 10,dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [75]:
x.max(), torch.max(x)

(tensor(90.), tensor(90.))

In [76]:
x.min(), torch.min(x)

(tensor(0.), tensor(0.))

In [78]:
x.mean(), torch.mean(x) # only mean are calculate on float32

(tensor(45.), tensor(45.))

In [79]:
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

In [81]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [82]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [83]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [86]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [87]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [88]:
x = torch.zeros(2,1,2,1,2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [90]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [94]:
y = torch.squeeze(x) # remove all single dimension
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [95]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [96]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [98]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [99]:
y = torch.unsqueeze(x, 1)
y, y.size()

(tensor([[[[[[0., 0.]],
 
            [[0., 0.]]]]],
 
 
 
 
         [[[[[0., 0.]],
 
            [[0., 0.]]]]]]),
 torch.Size([2, 1, 1, 2, 1, 2]))

In [102]:
x = torch.rand(224, 224, 3) #Image: height, width and colour chhanel
x.size()

torch.Size([224, 224, 3])

In [104]:
x_permute = x.permute(2,0,1)
x_permute.size()

torch.Size([3, 224, 224])

In [105]:
x

tensor([[[0.7525, 0.8879, 0.9424],
         [0.0016, 0.3758, 0.6077],
         [0.6972, 0.9996, 0.6968],
         ...,
         [0.9236, 0.4343, 0.7424],
         [0.6912, 0.0556, 0.3369],
         [0.2483, 0.5742, 0.8244]],

        [[0.5347, 0.3664, 0.2911],
         [0.7735, 0.4203, 0.0867],
         [0.9057, 0.2988, 0.9701],
         ...,
         [0.7261, 0.2017, 0.8517],
         [0.4252, 0.3942, 0.4016],
         [0.0688, 0.3904, 0.7307]],

        [[0.1145, 0.7593, 0.5935],
         [0.1637, 0.2563, 0.2080],
         [0.3015, 0.5149, 0.5793],
         ...,
         [0.4282, 0.0535, 0.4203],
         [0.6190, 0.5033, 0.0962],
         [0.6878, 0.0546, 0.5178]],

        ...,

        [[0.9046, 0.0851, 0.8612],
         [0.3488, 0.6781, 0.9949],
         [0.9518, 0.1201, 0.0392],
         ...,
         [0.9103, 0.4690, 0.2525],
         [0.9140, 0.3485, 0.3834],
         [0.0553, 0.1993, 0.4076]],

        [[0.8088, 0.4108, 0.4105],
         [0.0868, 0.8029, 0.5356],
         [0.

In [106]:
x[0,0,0] =100
x[0,0,0],x_permute[0,0,0]

(tensor(100.), tensor(100.))

In [108]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [109]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [112]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [116]:
x[:,0:2]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [122]:
x[:,:,1]

tensor([[2, 5, 8]])

In [123]:
x[:,1,1]

tensor([5])

In [133]:
torch.manual_seed(42)
x = torch.rand(3,4)
y = torch.rand(3,4)
print(x)
print('\n')
print(y)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [134]:
import numpy as np

In [135]:
array = np.arange(1.0,8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [141]:
tensor = torch.from_numpy(array).type(torch.float32).to('cuda')
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], device='cuda:0')

In [143]:
tensor = torch.ones(10)
array = tensor.numpy()
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [144]:
tensor = tensor + 1
tensor, array

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [151]:
torch.rand(3,3)


tensor([[0.6790, 0.9155, 0.2418],
        [0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

# Check for GPU access with PyTorch

In [152]:
import torch
torch.cuda.is_available()

True

In [159]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [154]:
torch.cuda.device_count()

1

In [155]:
cuda2 = torch.device('cuda:2')

In [156]:
cuda2

device(type='cuda', index=2)

In [157]:
cuda = torch.device('cuda')     # Default CUDA device
cuda0 = torch.device('cuda:0')
cuda2 = torch.device('cuda:2')  # GPU 2 (these are 0-indexed)

x = torch.tensor([1., 2.], device=cuda0)
# x.device is device(type='cuda', index=0)
y = torch.tensor([1., 2.]).cuda()
# y.device is device(type='cuda', index=0)

with torch.cuda.device(1):
    # allocates a tensor on GPU 1
    a = torch.tensor([1., 2.], device=cuda)

    # transfers a tensor from CPU to GPU 1
    b = torch.tensor([1., 2.]).cuda()
    # a.device and b.device are device(type='cuda', index=1)

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.tensor([1., 2.]).to(device=cuda)
    # b.device and b2.device are device(type='cuda', index=1)

    c = a + b
    # c.device is device(type='cuda', index=1)

    z = x + y
    # z.device is device(type='cuda', index=0)

    # even within a context, you can specify the device
    # (or give a GPU index to the .cuda call)
    d = torch.randn(2, device=cuda2)
    e = torch.randn(2).to(cuda2)
    f = torch.randn(2).cuda(cuda2)

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [158]:
import argparse
import torch

parser = argparse.ArgumentParser(description= 'Pytorch Example')
parser.add_argument('--disable-cuda', action = 'store_true',
                    help = 'Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device= torch.device('cuda')

else:
    args.device= torch.device('cpu')

usage: ipykernel_launcher.py [-h] [--disable-cuda]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\Nihar\AppData\Roaming\jupyter\runtime\kernel-96c5d2e0-0ebe-44d0-97d0-9bd893194a1e.json


SystemExit: 2

C:\Users\Nihar\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [160]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [161]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [162]:
tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [164]:
tensor_to_gpu.cpu().numpy()

array([1, 2, 3], dtype=int64)