In [1]:
import torch
torch.__version__

'2.2.0+cu118'

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3070 Laptop GPU'

In [4]:
# using empty
a = torch.empty(2, 3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.0557, 0.7709, 0.5153],
        [0.5613, 0.4716, 0.5679]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(0, 20, 10)

tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [15]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x.to(torch.float64))

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

In [20]:
# Create a tensor of shape (3, 2)
input_tensor = torch.zeros(3, 2)

# Generate a tensor with the same shape as input_tensor, filled with random values
random_tensor = torch.rand_like(input_tensor)

print("Random Tensor:")
print(random_tensor)


Random Tensor:
tensor([[0.2239, 0.3023],
        [0.1784, 0.8238],
        [0.5557, 0.9770]])


In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

C:\Users\Nihar\AppData\Local\Temp\ipykernel_22860\2167296389.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.0,2.0,3.0], dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [25]:
x.to(float)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [26]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [27]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [28]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [29]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [30]:
(x*100)//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [31]:
((x*100)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [32]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [33]:
x^2

tensor([[3, 0, 1],
        [6, 7, 4]])

In [34]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
x^10

tensor([[11,  8,  9],
        [14, 15, 12]])

In [36]:
x^2

tensor([[3, 0, 1],
        [6, 7, 4]])

In [37]:
torch.log10(x)

tensor([[0.0000, 0.3010, 0.4771],
        [0.6021, 0.6990, 0.7782]])

In [38]:
torch.log2(x)

tensor([[0.0000, 1.0000, 1.5850],
        [2.0000, 2.3219, 2.5850]])

In [39]:
x^3

tensor([[2, 1, 0],
        [7, 6, 5]])

In [40]:
x^4

tensor([[5, 6, 7],
        [0, 1, 2]])

In [42]:
x^5

tensor([[4, 7, 6],
        [1, 0, 3]])

In [46]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [44]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [45]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [47]:
torch.pow(c,2)

tensor([ 1,  4,  9, 16])

In [48]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [49]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [50]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [58]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [57]:
# clamp
torch.clamp(d,2, 4)

tensor([2.0000, 2.3000, 3.7000, 4.0000])

In [67]:
# Reduction

e = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [68]:
# sum
torch.sum(e)

tensor(28.)

In [69]:
torch.sum(e, dim= 0)

tensor([ 3., 14., 11.])

In [70]:
torch.sum(e, dim= 1)

tensor([16., 12.])

In [71]:
torch.mean(e)

tensor(4.6667)

In [72]:
torch.mean(e, dim= 0)

tensor([1.5000, 7.0000, 5.5000])

In [73]:
# median
torch.median(e)

tensor(4.)

In [74]:
torch.median(e, dim= 0)

torch.return_types.median(
values=tensor([0., 5., 4.]),
indices=tensor([1, 1, 0]))

In [75]:
torch.prod(e)

tensor(0.)

In [76]:
torch.var(e)

tensor(9.8667)

In [77]:
torch.std(e)

tensor(3.1411)

In [78]:
torch.argmax(e)

tensor(1)

In [79]:
torch.argmin(e)

tensor(3)

In [81]:
torch.transpose(e, 0, 1)

tensor([[3., 0.],
        [9., 5.],
        [4., 7.]])

In [83]:
torch.trapz(e)

tensor([12.5000,  8.5000])

In [92]:
# determinant
h = torch.randint(size=(3,3),low = 1, high = 20, dtype= torch.float32)
h

tensor([[16., 17.,  7.],
        [ 7.,  4.,  2.],
        [12.,  7.,  9.]])

In [93]:
torch.det(h)

tensor(-304.)

In [94]:
torch.inverse(h)

tensor([[-0.0724,  0.3421, -0.0197],
        [ 0.1283, -0.1974, -0.0559],
        [-0.0033, -0.3026,  0.1809]])

In [96]:
i = torch.randint(size=(3,3),low = 1, high = 20, dtype= torch.float32)
j = torch.randint(size=(3,3),low = 1, high = 20, dtype= torch.float32)

In [97]:
i>j

tensor([[False, False,  True],
        [False,  True,  True],
        [False, False, False]])

In [98]:
i<j

tensor([[ True,  True, False],
        [ True, False, False],
        [ True,  True,  True]])

In [99]:
i==j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [100]:
i!=j

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [101]:
i<=j

tensor([[ True,  True, False],
        [ True, False, False],
        [ True,  True,  True]])

In [102]:
i>=j

tensor([[False, False,  True],
        [False,  True,  True],
        [False, False, False]])

In [104]:
i

tensor([[ 7.,  8., 18.],
        [ 4., 10., 18.],
        [ 2.,  7., 10.]])

In [103]:
# log
torch.log(i)

tensor([[1.9459, 2.0794, 2.8904],
        [1.3863, 2.3026, 2.8904],
        [0.6931, 1.9459, 2.3026]])

In [105]:
# exp
torch.exp(i)

tensor([[1.0966e+03, 2.9810e+03, 6.5660e+07],
        [5.4598e+01, 2.2026e+04, 6.5660e+07],
        [7.3891e+00, 1.0966e+03, 2.2026e+04]])

In [106]:
# sqrt
torch.sqrt(i)

tensor([[2.6458, 2.8284, 4.2426],
        [2.0000, 3.1623, 4.2426],
        [1.4142, 2.6458, 3.1623]])

In [107]:
# sigmoid
torch.sigmoid(i)

tensor([[0.9991, 0.9997, 1.0000],
        [0.9820, 1.0000, 1.0000],
        [0.8808, 0.9991, 1.0000]])

In [113]:
# Softmax
torch.softmax(i, dim=0)

tensor([[9.4650e-01, 1.1420e-01, 4.9992e-01],
        [4.7123e-02, 8.4379e-01, 4.9992e-01],
        [6.3775e-03, 4.2010e-02, 1.6770e-04]])

In [114]:
# relu
torch.relu(i)

tensor([[ 7.,  8., 18.],
        [ 4., 10., 18.],
        [ 2.,  7., 10.]])

# Inplace Operation

In [120]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [121]:
m+n

tensor([[1.6124, 0.6556, 0.4835],
        [0.8263, 1.5441, 0.8216]])

In [118]:
m = m+n
m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [122]:
m.add_(n)

tensor([[1.6124, 0.6556, 0.4835],
        [0.8263, 1.5441, 0.8216]])

In [123]:
torch.relu(m)

tensor([[1.6124, 0.6556, 0.4835],
        [0.8263, 1.5441, 0.8216]])

In [124]:
m.relu_()

tensor([[1.6124, 0.6556, 0.4835],
        [0.8263, 1.5441, 0.8216]])

In [125]:
m

tensor([[1.6124, 0.6556, 0.4835],
        [0.8263, 1.5441, 0.8216]])

In [126]:
b = a

In [127]:
b

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [134]:
a[1][0] = 12
a

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 1.2000e+01,  0.0000e+00,  0.0000e+00]])

In [130]:
b

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 1.0000e+00,  0.0000e+00,  0.0000e+00]])

In [131]:
b = a.clone()
b

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 1.0000e+00,  0.0000e+00,  0.0000e+00]])

In [135]:
b

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 1.0000e+00,  0.0000e+00,  0.0000e+00]])

In [136]:
id(a)

2130345892256

In [137]:
id(b)

2131283988784

In [138]:
torch.cuda.is_available()

True

In [139]:
device = torch.device('cuda')

# Tensor opertion on GPU

In [141]:
 torch.rand((2,3), device = device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [142]:
a.to(device)

tensor([[-5.3310e-15,  1.7012e-42,  0.0000e+00],
        [ 1.2000e+01,  0.0000e+00,  0.0000e+00]], device='cuda:0')

In [144]:
b = a.to(device)


In [145]:
b+5

tensor([[ 5.,  5.,  5.],
        [17.,  5.,  5.]], device='cuda:0')

In [149]:
import time

size = 10000

mat_c1 = torch.randn(size, size)
mat_c2 = torch.randn(size, size)

st = time.time()
result_c = torch.matmul(mat_c1, mat_c2)

cpu_time = time.time() - st

print(f" {cpu_time: .4f} seconds")

mat_g1 = mat_c1.to(device)
mat_g2 = mat_c2.to(device)

st = time.time()
result_c = torch.matmul(mat_g1, mat_g2)

gpu_time = time.time() - st

print(f" {gpu_time: .4f} seconds")

print(f"Speed: {cpu_time/gpu_time}")

  59.6323 seconds
  0.0010 seconds
Speed: 59665.06583969466


In [150]:
# Reshaping

a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [151]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [152]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [154]:
b = torch.rand(2,3,4)
b

tensor([[[0.5330, 0.3768, 0.2254, 0.6387],
         [0.1616, 0.4012, 0.5106, 0.3696],
         [0.6231, 0.1191, 0.1854, 0.0566]],

        [[0.5113, 0.8340, 0.3405, 0.8644],
         [0.9594, 0.7425, 0.7045, 0.1476],
         [0.1044, 0.9013, 0.0787, 0.3159]]])

In [155]:
# Permute
b.permute(2,0,1) 

tensor([[[0.5330, 0.1616, 0.6231],
         [0.5113, 0.9594, 0.1044]],

        [[0.3768, 0.4012, 0.1191],
         [0.8340, 0.7425, 0.9013]],

        [[0.2254, 0.5106, 0.1854],
         [0.3405, 0.7045, 0.0787]],

        [[0.6387, 0.3696, 0.0566],
         [0.8644, 0.1476, 0.3159]]])

In [157]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [163]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [164]:
c.unsqueeze(0).squeeze(0).shape

torch.Size([226, 226, 3])

In [166]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [167]:
import numpy as np

In [168]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [170]:
b = a.numpy()
b

array([1, 2, 3], dtype=int64)

In [171]:
torch.from_numpy(b)


tensor([1, 2, 3])