In [3]:
x = list(range(100))
  


l = [detection for detection in x if detection %2 == 0]
l

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [6]:
from collections import Counter

amount_bboxes = Counter([gt[0] for gt in ground_truths])
amount_bboxes

NameError: name 'ground' is not defined

In [7]:
import torch

In [9]:
torch.zeros(3)

tensor([0., 0., 0.])

In [19]:
torch.cat((torch.tensor([1]), torch.tensor([0.5])))

tensor([1.0000, 0.5000])

In [15]:
x = torch.randn(2, 3)
x

tensor([[-0.7825, -0.1324,  0.5445],
        [ 0.3120,  0.0509,  0.7774]])

In [16]:
torch.cat((x, x, x), 0)

tensor([[-0.7825, -0.1324,  0.5445],
        [ 0.3120,  0.0509,  0.7774],
        [-0.7825, -0.1324,  0.5445],
        [ 0.3120,  0.0509,  0.7774],
        [-0.7825, -0.1324,  0.5445],
        [ 0.3120,  0.0509,  0.7774]])

In [20]:
x = torch.rand(10)
x

tensor([0.6578, 0.7782, 0.4023, 0.5376, 0.9140, 0.3579, 0.9029, 0.9248, 0.3441,
        0.4091])

In [21]:
y = torch.rand(10)
y

tensor([0.8900, 0.8206, 0.8230, 0.2112, 0.7098, 0.7101, 0.9210, 0.6318, 0.4401,
        0.5658])

In [24]:
torch.trapz(x, y)

tensor(-0.1794)

In [25]:
y = torch.ones(3, 3)
>>> x = torch.tensor([1, 3, 6])
>>> torch.trapezoid(y, x)

tensor([5., 5., 5.])

In [27]:
y = torch.ones(3, 3)
>>> x = torch.tensor([1, 3, 6])
>>> torch.trapz(y, x)

tensor([5., 5., 5.])

In [28]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])