In [1]:
import torch
import torch.nn as nn

In [3]:
nn.ModuleList()

ModuleList()

In [4]:
import torch
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
reshaped_x = x.reshape(2, 3)  # New shape [2, 3]
print(reshaped_x)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape [2, 2, 2]
permuted_x = x.permute(1,2, 0)  # New shape [2, 2, 2] but different ordering
print(permuted_x)


tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [6]:
x

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [7]:
permuted_x = x.permute(1,0,2)  # New shape [2, 2, 2] but different ordering
print(permuted_x)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [13]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
permuted_x = x.permute(1, 2, 0)
permuted_x

tensor([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],

        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]])